apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: 
spec:
  selector:
    app: sample-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP